stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script: 
        - echo "Building"
        - python3 MyEventManager.py

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - python3 MyEventManagerTest.py
